/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useLoader } from "@react-three/fiber";

import { GLTFLoader } from "three/examples/jsm/Addons.js";

const Bamboo = () => {
  const model = useLoader(GLTFLoader, "./models/bamboo.glb");

  model.scene.traverse((obj) => {
    if (obj.isMesh) {
      obj.castShadow = true;
    }
  });

  return <primitive object={model.scene} />;
};

export default Bamboo;
// type GLTFResult = GLTF & {
//   nodes: {
//     Bark01_5: THREE.Mesh;
//     Branch01_5: THREE.Mesh;
//     Leaf01_5: THREE.Mesh;
//     Leaf02_5: THREE.Mesh;
//   };
//   materials: {
//     Bark01_SHD: THREE.MeshPhysicalMaterial;
//     Branch01_SHD: THREE.MeshPhysicalMaterial;
//     Leaf01_su_SHD: THREE.MeshPhysicalMaterial;
//     Leaf02_su_SHD: THREE.MeshPhysicalMaterial;
//   };
// };

// export function BambooModel(props: JSX.IntrinsicElements["group"]) {
//   const { nodes, materials } = useGLTF("/models/bamboo.glb") as GLTFResult;
//   const [color, setColor] = useState("green");

//   return (
//     <group {...props} dispose={null}>
//       <group position={[-0.003, 0.051, 0.257]} scale={0.01}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Bark01_5.geometry}
//           material={materials.Bark01_SHD}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Branch01_5.geometry}
//           material={materials.Branch01_SHD}
//           //
//           material-color={color}
//           onClick={() => (color != "red" ? setColor("red") : setColor("white"))}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Leaf01_5.geometry}
//           material={materials.Leaf01_su_SHD}
//           //
//           material-color={color}
//           onClick={() => (color != "red" ? setColor("red") : setColor("white"))}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Leaf02_5.geometry}
//           material={materials.Leaf02_su_SHD}
//           //
//           material-color={color}
//           onClick={() => (color != "red" ? setColor("red") : setColor("white"))}
//         />
//       </group>
//     </group>
//   );
// }

// useGLTF.preload("/models/bamboo.glb");
